package:
    name: acs_replica_intake
    version: 1.3

source:
    path: .

build:
    number: 1
    noarch: python
    script: python -m pip install --no-deps .

requirements:
    host:
        - python
    run:
        - python
        - intake
        - intake-esm
